name: diff-id
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  id2204:
    runs-on: ubuntu-22.04
    outputs:
      passwd2204: ${{ steps.passwd2204.outputs.passwd2204 }}
      group2204: ${{ steps.group2204.outputs.group2204 }}

    steps:
      - uses: actions/checkout@v3

      - name: Set passwd to outputs
        id: passwd2204
        run: |
          echo 'passwd2204<<EOF' >> $GITHUB_OUTPUT
          cat /etc/passwd >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        shell: bash

      - name: Set group to outputs
        id: group2204
        run: |
          echo 'group2204<<EOF' >> $GITHUB_OUTPUT
          cat /etc/group >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        shell: bash

  id2004:
    runs-on: ubuntu-20.04
    outputs:
      passwd2004: ${{ steps.passwd2004.outputs.passwd2004 }}
      group2004: ${{ steps.group2004.outputs.group2004 }}

    steps:
      - uses: actions/checkout@v3

      - name: Set passwd to outputs
        id: passwd2004
        run: |
          echo 'passwd2004<<EOF' >> $GITHUB_OUTPUT
          cat /etc/passwd >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        shell: bash

      - name: Set group to outputs
        id: group2004
        run: |
          echo 'group2004<<EOF' >> $GITHUB_OUTPUT
          cat /etc/group >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        shell: bash

  print:
    runs-on: ubuntu-latest
    needs: 
      - id2204
      - id2004
    steps:
      - uses: actions/checkout@v3

      - name: Diff passwd 2204 and 2004
        run: |
          echo "--- passwd 2004"
          echo "${PASSWD2004}"
          echo "---"
          echo "--- passwd 2204"
          echo "${PASSWD2204}"
          echo "---"
          echo "--- diff 2202 2204"
          diff <(echo "${PASSWD2004}") <(echo "${PASSWD2204}") || true
        shell: bash
        env:
          PASSWD2004: ${{needs.id2004.outputs.passwd2004}}
          PASSWD2204: ${{needs.id2204.outputs.passwd2204}}


      - name: Diff group 2204 and 2004
        run: |
          echo "--- group 2004"
          echo "${GROUP2004}"
          echo "---"
          echo "--- group 2204"
          echo "${GROUP2204}"
          echo "---"
          echo "--- diff 2202 2204"
          diff <(echo "${GROUP2004}") <(echo "${GROUP2204}") || true
        shell: bash
        env:
          GROUP2004: ${{needs.id2004.outputs.group2004}}
          GROUP2204: ${{needs.id2204.outputs.group2204}}


